package es.mgamallo.prometeo;

import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;

import javax.swing.DefaultListModel;

public class VentanaListaPdfs extends javax.swing.JFrame {

    /**
     * Creates new form VentanaListaPdfs
     */
    public VentanaListaPdfs() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaPdfs = new javax.swing.JList();
        modelo = new DefaultListModel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Lista Pdfs");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(200, 500));

        listaPdfs.setBackground(new java.awt.Color(255, 248, 168));
        listaPdfs.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        listaPdfs.setModel(modelo);
        listaPdfs.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        
        listaPdfs.addMouseListener(new MouseAdapter() {
        	public void mouseClicked(MouseEvent ev){
        		if(ev.getButton() == 2){ 
        			// Boton central
        			System.out.println("pulsado el boton central");
        		}
        		else if(ev.getButton() == 1){
        			// Boton izquierdo
        			System.out.println("pulsado el boton izquierdo");
        			
        			pulsarListaPdfs();
        			
        		}
        		else{
        			// Boton derecho
        			System.out.println("Pulsado el boton derecho");
        		}
        	}
		});
        
        jScrollPane1.setViewportView(listaPdfs);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    
    //	Métodos propios
    
    public void setModel(DefaultListModel modelo){
    	this.modelo = modelo;
    }
    
    
    public void pulsarListaPdfs(){
  		
		int numArchivo = listaPdfs.getSelectedIndex();
		int tamañoLista = listaPdfs.getModel().getSize();
		
		InicioIanus.pdfSeleccionado = numArchivo;
		


		
		InicioIanus.tandaDePdfs[0] = new File(InicioIanus.rutaCompletaPdfs[numArchivo]);
		
		Inicio.navegador1.webBrowser.setVisible(true);
		Inicio.navegador1.setPdf(InicioIanus.tandaDePdfs[0].getAbsolutePath().toString(),
				InicioIanus.tandaDePdfs[0].getName().toString(), new Color(80,200,120));
			
		
		if(InicioIanus.documentacion == 2 || InicioIanus.documentacion == 3){
			InicioIanus.teclaAzul1.setText(InicioIanus.documentos[numArchivo].nhc);
			InicioIanus.teclaAzul2.setText(InicioIanus.documentos[numArchivo].nombreNormalizado);
 			
 			
			InicioIanus.botonIanus.setText(InicioIanus.nhcIanus);
 			InicioIanus.botonServicio.setText(InicioIanus.documentos[numArchivo].servicio);
 			InicioIanus.botonNombreNormalizado.setText(InicioIanus.documentos[numArchivo].nombreNormalizado);
 			
 			if(!InicioIanus.comboServicios.getSelectedItem().toString().equals(InicioIanus.documentos[numArchivo].servicio)){
 				InicioIanus.botonServicio.setBackground(Color.red);
 				Inicio.navegador1.ocrPanel.setBackground(Color.yellow);
 			}
 			else{
 				InicioIanus.botonServicio.setBackground(Color.green);
 				Inicio.navegador1.ocrPanel.setBackground(new Color(255,222,173));
 			}
 			
 			if(numArchivo > 1){
 				if(!InicioIanus.documentos[numArchivo].nhc.equals(InicioIanus.documentos[numArchivo-1].nhc)){
     				Inicio.navegador1.ocrPanel.setBackground(Color.red);
     				Inicio.navegador1.webBrowserPanel.setBackground(Color.red);
     			}
     			else{
     				Inicio.navegador1.ocrPanel.setBackground(new Color(255,222,173));
     				Inicio.navegador1.webBrowserPanel.setBackground(new Color(80,200,120));
     			}
 			}
 			
 			
 			InicioIanus.comboServicios.setSelectedItem(InicioIanus.documentos[numArchivo].servicio);
			
			
		}
		        		

    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaListaPdfs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaListaPdfs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaListaPdfs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaListaPdfs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaListaPdfs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    public javax.swing.JList listaPdfs;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private DefaultListModel modelo;
    // End of variables declaration                   
}
