package es.mgamallo.prometeo;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;

import javax.swing.DefaultListModel;

public class VentanaNombres extends javax.swing.JFrame {

	/**
	 * Creates new form VentanaNombres
	 */
	
	protected static final String LS = System.getProperty("line.separator");

	int contador = 1;

	String[] listaServicios;
	String[] listaNombresDocumentos;
	String[][] tablaDocumentos;
	String[][] tablaHabituales;
	
	String nombreDocumentoSeleccionado = "";

	int tamañoActualListaNombresDocumentos = 0;

	DefaultListModel listaModelNombresServicio;

	public VentanaNombres(String[] listaServicios,
			String[] listaNombresDocumentos, String[][] tablaDocumentos,
			String[][] tablaHabituales) {

		this.listaServicios = listaServicios;
		this.listaNombresDocumentos = listaNombresDocumentos;
		this.tablaDocumentos = tablaDocumentos;
		this.tablaHabituales = tablaHabituales;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		panelPrincipal = new javax.swing.JPanel();
		jSplitPane1 = new javax.swing.JSplitPane();
		jSplitPane2 = new javax.swing.JSplitPane();
		panelComunes = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		scrollComunes = new javax.swing.JScrollPane();
		listaComunes = new javax.swing.JList();
		checkTodos = new javax.swing.JCheckBox();
		panelHab1 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		scrollHab1 = new javax.swing.JScrollPane();
		listaHab1 = new javax.swing.JList();
		jSplitPane3 = new javax.swing.JSplitPane();
		panelHab2 = new javax.swing.JPanel();
		jLabel3 = new javax.swing.JLabel();
		scrollHab2 = new javax.swing.JScrollPane();
		listaHab2 = new javax.swing.JList();
		panelServicio = new javax.swing.JPanel();
		jLabel4 = new javax.swing.JLabel();
		scrollServicio = new javax.swing.JScrollPane();
		listaServicio = new javax.swing.JList();
		comboServicio = new javax.swing.JComboBox();

		setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
		setTitle("Nombres");
		setPreferredSize(new java.awt.Dimension(1024, 380));

		jSplitPane1.setDividerLocation(512);

		jSplitPane2.setDividerLocation(256);

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel1.setText("Comunes");

		listaComunes.setBackground(new java.awt.Color(255, 255, 204));
		listaComunes.setModel(InicioIanus.listaModelNombresComunes);
		listaComunes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
		scrollComunes.setViewportView(listaComunes);
		
		checkTodos.setText("Todos");
		checkTodos.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent ev) {
				// TODO Auto-generated method stub
				if (checkTodos.isSelected()) {
					listaComunes.removeAll();
					listaComunes
							.setModel(InicioIanus.listaModelTodosLosNombres);
				} else {
					listaComunes.removeAll();
					listaComunes.setModel(InicioIanus.listaModelNombresComunes);
				}
			}
		});

		javax.swing.GroupLayout panelComunesLayout = new javax.swing.GroupLayout(
				panelComunes);
		panelComunes.setLayout(panelComunesLayout);
		panelComunesLayout
				.setHorizontalGroup(panelComunesLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(scrollComunes)
						.addGroup(
								panelComunesLayout
										.createSequentialGroup()
										.addComponent(jLabel1)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												130, Short.MAX_VALUE)
										.addComponent(checkTodos)
										.addGap(18, 18, 18)));
		panelComunesLayout
				.setVerticalGroup(panelComunesLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								panelComunesLayout
										.createSequentialGroup()
										.addGroup(
												panelComunesLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel1)
														.addComponent(
																checkTodos))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												scrollComunes,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												271, Short.MAX_VALUE)));

		jSplitPane2.setLeftComponent(panelComunes);

		jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel2.setText("Habituales 1");

		listaHab1.setBackground(new java.awt.Color(255, 255, 204));
		listaHab1.setModel(InicioIanus.listaModelHabituales1);
		listaHab1
				.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
		scrollHab1.setViewportView(listaHab1);

		javax.swing.GroupLayout panelHab1Layout = new javax.swing.GroupLayout(
				panelHab1);
		panelHab1.setLayout(panelHab1Layout);
		panelHab1Layout.setHorizontalGroup(panelHab1Layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						panelHab1Layout.createSequentialGroup()
								.addComponent(jLabel2)
								.addGap(0, 179, Short.MAX_VALUE))
				.addComponent(scrollHab1));
		panelHab1Layout
				.setVerticalGroup(panelHab1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								panelHab1Layout
										.createSequentialGroup()
										.addComponent(jLabel2)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												scrollHab1,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												276, Short.MAX_VALUE)));

		jSplitPane2.setRightComponent(panelHab1);

		jSplitPane1.setLeftComponent(jSplitPane2);

		jSplitPane3.setDividerLocation(256);

		jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel3.setText("Habituales 2");

		listaHab2.setBackground(new java.awt.Color(255, 255, 204));
		listaHab2.setModel(InicioIanus.listaModelHabituales2);
		listaHab2
				.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
		scrollHab2.setViewportView(listaHab2);

		javax.swing.GroupLayout panelHab2Layout = new javax.swing.GroupLayout(
				panelHab2);
		panelHab2.setLayout(panelHab2Layout);
		panelHab2Layout.setHorizontalGroup(panelHab2Layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						panelHab2Layout.createSequentialGroup()
								.addComponent(jLabel3)
								.addGap(0, 98, Short.MAX_VALUE))
				.addComponent(scrollHab2));
		panelHab2Layout
				.setVerticalGroup(panelHab2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								panelHab2Layout
										.createSequentialGroup()
										.addComponent(jLabel3)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												scrollHab2,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												276, Short.MAX_VALUE)));

		jSplitPane3.setLeftComponent(panelHab2);

		jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel4.setText("Propios del Servicio");

		listaServicio.setBackground(new java.awt.Color(255, 255, 204));

		listaServicio.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
		scrollServicio.setViewportView(listaServicio);

		listaModelNombresServicio = new DefaultListModel();

		comboServicio.setModel(InicioIanus.listaModelServicios);
		comboServicio.setSelectedIndex(0);
		listaServicio.setModel(getDocServicio(comboServicio.getSelectedItem().toString()));

		comboServicio.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent arg0) {
				// TODO Auto-generated method stub
				listaServicio.setModel(getDocServicio(comboServicio
						.getSelectedItem().toString()));
			}
		});
		
		
		//	Eventos listas
		
		listaComunes.addMouseListener(new MouseAdapter() {
			public void mouseClicked(MouseEvent ev){
				nombreDocumentoSeleccionado = listaComunes.getSelectedValue().toString();
				clickListas(ev, 0);
			}
		});
		
		listaHab1.addMouseListener(new MouseAdapter() {
			public void mouseClicked(MouseEvent ev){
				nombreDocumentoSeleccionado = listaHab1.getSelectedValue().toString();
				clickListas(ev,1);
			}
		});
		
		listaHab2.addMouseListener(new MouseAdapter() {
			public void mouseClicked(MouseEvent ev){
				nombreDocumentoSeleccionado = listaHab2.getSelectedValue().toString();
				clickListas(ev,2);
			}
		});
		
		listaServicio.addMouseListener(new MouseAdapter() {
			public void mouseClicked(MouseEvent ev){
				nombreDocumentoSeleccionado = listaServicio.getSelectedValue().toString();
				clickListas(ev,3);
			}
		});
		
		

		javax.swing.GroupLayout panelServicioLayout = new javax.swing.GroupLayout(
				panelServicio);
		panelServicio.setLayout(panelServicioLayout);
		panelServicioLayout
				.setHorizontalGroup(panelServicioLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								panelServicioLayout
										.createSequentialGroup()
										.addComponent(jLabel4)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(comboServicio, 0, 199,
												Short.MAX_VALUE))
						.addComponent(scrollServicio));
		panelServicioLayout
				.setVerticalGroup(panelServicioLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								panelServicioLayout
										.createSequentialGroup()
										.addGroup(
												panelServicioLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel4)
														.addComponent(
																comboServicio,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												scrollServicio,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												270, Short.MAX_VALUE)));

		jSplitPane3.setRightComponent(panelServicio);

		jSplitPane1.setRightComponent(jSplitPane3);

		javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(
				panelPrincipal);
		panelPrincipal.setLayout(panelPrincipalLayout);
		panelPrincipalLayout.setHorizontalGroup(panelPrincipalLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jSplitPane1));
		panelPrincipalLayout.setVerticalGroup(panelPrincipalLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jSplitPane1));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>

	
	
	public DefaultListModel getDocServicio(String servicio) {

		listaModelNombresServicio.removeAllElements();

		int numServicio = 0;
		for (int i = 0; i < listaServicios.length; i++) {
			if (listaServicios[i].equals(servicio)) {
				numServicio = i;
				break;
			}
		}

		for (int i = 0; i < listaNombresDocumentos.length; i++) {
			if (!tablaDocumentos[i][numServicio].toLowerCase().equals("")) {
				if (tablaHabituales[i][0].toLowerCase().equals("n")
						&& tablaHabituales[i][1].toLowerCase().equals("n")
						&& tablaHabituales[i][2].toLowerCase().equals("n")
						&& tablaHabituales[i][3].toLowerCase().equals("n")) {
					listaModelNombresServicio
							.addElement(listaNombresDocumentos[i]);
				}
			}
		}

		return listaModelNombresServicio;
	}

	
	private void clickListas(MouseEvent ev, int tipoLista){
		
		for(int i=0;i<4;i++){
			if(tipoLista != 0){
				listaComunes.clearSelection();
			}
			if(tipoLista != 1){
				listaHab1.clearSelection();
			}
			if(tipoLista != 2){
				listaHab2.clearSelection();
			}
			if(tipoLista != 3){
				listaServicio.clearSelection();

			}
		}
		
		Inicio.vExplorador.asociaDocumento(nombreDocumentoSeleccionado);

		
		/*
		InicioIanus.documentoActivo.nombreDocumento = nombreDocumentoSeleccionado;
		System.out.println(InicioIanus.documentoActivo.nombreDocumento);
		*/
	}
	

	
	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(VentanaNombres.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(VentanaNombres.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(VentanaNombres.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(VentanaNombres.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new VentanaNombres(null, null, null, null).setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JCheckBox checkTodos;
	public javax.swing.JComboBox comboServicio;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JSplitPane jSplitPane1;
	private javax.swing.JSplitPane jSplitPane2;
	private javax.swing.JSplitPane jSplitPane3;
	private javax.swing.JList listaComunes;
	private javax.swing.JList listaHab1;
	private javax.swing.JList listaHab2;
	private javax.swing.JList listaServicio;
	private javax.swing.JPanel panelComunes;
	private javax.swing.JPanel panelHab1;
	private javax.swing.JPanel panelHab2;
	private javax.swing.JPanel panelPrincipal;
	private javax.swing.JPanel panelServicio;
	private javax.swing.JScrollPane scrollComunes;
	private javax.swing.JScrollPane scrollHab1;
	private javax.swing.JScrollPane scrollHab2;
	private javax.swing.JScrollPane scrollServicio;
	// End of variables declaration
}
